#!/system/xbin/bash
f="/sys/devices/system/cpu/cpu0/cpufreq"

for F in $f/cpuinfo* $f/scaling* $f/screen*; do
    [ ! -e $F ] && continue
    basename $F
    for x in /sys/devices/system/cpu/cpu[0-9]*; do
      cpu=`basename $x`
      percpu=`echo $F | sed "s/cpu0/$cpu/g"`
      echo -e "\t\t$cpu = $(cat $percpu)"
    done
done
