#!/bin/bash

# Configuration
SOURCE_DIR=$"$(pwd)"
VANIR=$"m/n71"
SUB_BRANCH=$"remotes/vanir/n71-subs712"
REMOTE_BRANCH=$"cm-14.1"


echo "YOU NEED TO RUN THIS FROM YOUR BUILD DIRECTORY"
sleep 3
echo ""
echo ""

# Need a Vanir resolution.  
echo "FWB"
cd $SOURCE_DIR/frameworks/base
git merge $SUB_BRANCH --no-commit
echo "Contacts"
cd $SOURCE_DIR/packages/apps/Contacts
git merge $SUB_BRANCH --no-commit
echo "Settings"
cd $SOURCE_DIR/packages/apps/Settings
git merge $SUB_BRANCH --no-commit


# Now the clean merges
echo ""
echo "Fetch-Sex-Magic"
# Masochism loops
substratum() {
cat<<EOF
frameworks_native
packages_apps_ContactsCommon
packages_apps_Dialer
packages_apps_ExactCalculator
packages_apps_PackageInstaller
packages_apps_PhoneCommon
system_core
system_sepolicy
packages_apps_Contacts
packages_apps_Settings
frameworks_base
EOF
}

# Let's merge it
substratum | while read u
do
z=$(echo ${u} | sed -e 's/_/\//g')
cd $SOURCE_DIR/${z}
git fetch https://github.com/LineageOMS/android_${u} $REMOTE_BRANCH
git merge FETCH_HEAD
done


echo ""
echo ""
echo "Remember to look for merge failures"
