#!/bin/bash

# Configuration
SOURCE_DIR="$(cd "$(dirname "$0")"/../../..; pwd)" #script location's parent, up 3
VANIR="$(cd $SOURCE_DIR/vendor/vanir; git branch -a | grep /m/ | awk '{print $1}' | sed 's/remotes\///g')"
SUB_BRANCH="remotes/vanir/n71-subs712"
REMOTE_BRANCH="$(repo info | grep -i 'manifest branch' | cut -d ':' -f 2 | sed 's/^\s*//g')"

# Need a Vanir resolution.  
echo "FWB"
cd "$SOURCE_DIR/frameworks/base"
git merge $SUB_BRANCH --no-edit
echo "Contacts"
cd "$SOURCE_DIR/packages/apps/Contacts"
git merge $SUB_BRANCH --no-edit
echo "Settings"
cd "$SOURCE_DIR/packages/apps/Settings"
git merge $SUB_BRANCH --no-edit


# Now the clean merges
echo ""
echo "Fetch-Sex-Magic"
# Masochism loops
substratum() {
cat<<EOF
frameworks_native
packages_apps_ContactsCommon
packages_apps_Dialer
packages_apps_ExactCalculator
packages_apps_PackageInstaller
packages_apps_PhoneCommon
system_core
system_sepolicy
packages_apps_Contacts
packages_apps_Settings
frameworks_base
EOF
}

# Let's merge it
substratum | while read u
do
z="$(echo "${u}" | sed -e 's/_/\//g')"
cd "$SOURCE_DIR/${z}"
git fetch "https://github.com/LineageOMS/android_${u}" "$REMOTE_BRANCH" && git merge FETCH_HEAD
done


echo ""
echo ""
echo "Remember to look for merge failures"
