#!/bin/bash
TOP=`dirname $0`/../../..
TOP=`cd $TOP && pwd`

get_mkfile_variable() {
  value=""
  for x in `cat $1 | sed 's/:=/=/g' | grep $2`; do
    value="`echo $x | cut -d '=' -f 2`"
  done
  echo $value
}

get_device_path() {
  device=`get_mkfile_variable $1 PRODUCT_NAME`
  for x in `cat $1 | grep inherit-product | grep device | cut -d ',' -f 2 | sed 's/)//g'`; do
    cmmk=$TOP/`dirname $x`/cm.mk
    [ -e $cmmk ] && echo $cmmk
  done
}

checkif() {
  if echo $line | grep -q ifeq || echo $line | grep -q ifneq; then
    if [ -e .inif ]; then
      echo "`expr $(cat .inif) + 1`" > .inif
    else
      echo 1 > .inif
    fi
    echo "`cat .inif` $line"
  fi
}

checkendif() {
  if echo $line | grep -q endif; then
    if [ -f .inif ]; then
      decremented=`expr $(cat .inif) - 1`
      if [ $decremented = 0 ]; then
        rm -f .inif
      else
        echo $decremented > .inif
      fi
      echo "$decremented $line"
    else
      echo "Invalid handling of ifs"
      exit 1
    fi
  fi
}

for x in $TOP/vendor/vanir/products/vanir_*.mk; do
  [ $x ] && grep -q PRODUCT_BUILD_PROP_OVERRIDES $x || continue
  RESULT=`mktemp`
  AFTER=`mktemp`
  grep -B100 PRODUCT_BUILD_PROP_OVERRIDES $x | grep -v PRODUCT_BUILD_PROP_OVERRIDES | while read line; do
    checkif
    checkendif
    echo $line >> $RESULT
  done
  grep -A100 PRODUCT_BUILD_PROP_OVERRIDES $x | while read line; do
    checkif
    if echo $line | grep -q PRODUCT_BUILD_PROP_OVERRIDES; then
      touch .inoverrides
    elif [ -f .inoverrides ]; then
      checkendif
      if ! echo $line | grep -q \\\\; then
        rm .inoverrides
        echo $line >> $AFTER
      fi
    else
      checkendif
      echo $line >> $AFTER
    fi
  done
  rm -f .inoverrides
  file=`get_device_path $x`
  if [ "$file" == "" ] || ! grep -q PRODUCT_BUILD_PROP_OVERRIDES $file; then
    rm -f $RESULT $AFTER
    continue
  fi
  grep -A100 PRODUCT_BUILD_PROP_OVERRIDES $file | while read line; do
    checkif
    checkendif
    if echo $line | grep -q PRODUCT_BUILD_PROP_OVERRIDES || echo $line | grep -q \\\\; then
      echo $line >> $RESULT
    fi
  done
  while [ -e .inif ]; do
    decremented=`expr $(cat .inif) - 1`
    if [ $decremented = 0 ]; then
      rm -f .inif
    else
      echo $decremented > .inif
    fi
    echo "$decremented $line"
    echo "endif" >> $RESULT
  done
  rm -f .inif
  cat $AFTER >> $RESULT
  md5tmp=`mktemp`
  md5sum $x > $md5tmp
  cp $RESULT ${RESULT}.tmp
  mv $x $RESULT
  mv ${RESULT}.tmp $x
  if ! md5sum --status -c $md5tmp; then
    echo -e "\n\n\n===== $x =====\n"
    if which colordiff >&/dev/null; then
      colordiff $x $RESULT
    else
      diff $x $RESULT
    fi
  fi
  rm -f $RESULT $AFTER $md5tmp
done

