#!/system/bin/sh

# Handle version downgrade errors caused by dirty flash from L5.0
#   TODO: decide if bumping the versions in these packages is sufficient

# this version of contacts provider crashes acore, because the version we build (as of 04/08/15) has db version 911.
# I have not investigated structural differences between the 5.0 and 5.1 versions to see if a blind version bump in the 5.1 source would alleviate this issue
if [ -e /data/data/com.android.providers.contacts ]; then
  contactsproviderdbversion=`sqlite3 /data/data/com.android.providers.contacts/databases/contacts2.db "pragma USER_VERSION;"`
  if [ "$contactsproviderdbversion" = "912" ]; then
    pm clear com.android.providers.contacts
  fi
fi
