#!/bin/bash
export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP
. $ANDROID_BUILD_TOP/vendor/vanir/tools/functions

pushd $1 > /dev/null

find ./ -name \*.apk | $HALFXARGS schedtool -B -n 1 -e ionice -n 1 $OPTICHARGER

popd > /dev/null
exit 0
